package com.agentgate.agent;

import static org.assertj.core.api.Assertions.assertThat;

import com.agentgate.agent.domain.Agent;
import com.agentgate.agent.repository.AgentRepository;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

/** Upgrading a database that already has agents from before agent definitions existed. */
@SpringBootTest
@ActiveProfiles("test")
class AgentSchemaUpgradeTest {

    private static final String URL = "jdbc:h2:mem:agent-upgrade;DB_CLOSE_DELAY=-1";

    @Autowired
    private AgentRepository agentRepository;

    @DynamicPropertySource
    static void existingDatabase(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", () -> URL);
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "update");
    }

    @BeforeAll
    static void createPreviousSchema() throws SQLException {
        try (Connection connection = DriverManager.getConnection(URL, "sa", "");
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table agents (
                        id bigint generated by default as identity primary key,
                        agent_id varchar(255) not null unique,
                        name varchar(255) not null,
                        api_key_hash varchar(255) not null,
                        max_risk_level varchar(255),
                        created_at timestamp(6) with time zone)""");
            statement.execute("insert into agents (agent_id, name, api_key_hash) values ('old-agent', 'Old', 'h')");
        }
    }

    @Test
    void existingAgentsGetDefinitionVersionZero() {
        List<Agent> agents = agentRepository.findAll();

        assertThat(agents).extracting(Agent::getAgentId).containsExactly("old-agent");
        assertThat(agents.get(0).getLatestDefinitionVersion()).isZero();
    }
}
