-- Baseline schema: the tables as of the switch from Hibernate ddl-auto to Flyway.
-- Written to also run on databases that ddl-auto already created (everything is "if not exists"),
-- so existing installations and new ones end up at the same schema.

create table if not exists agent_definition_versions (
    version integer not null,
    agent_id bigint not null,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    definition jsonb not null,
    primary key (id),
    unique (agent_id, version)
);

create table if not exists agents (
    latest_definition_version integer default 0 not null,
    api_key_issued_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    description varchar(1000),
    agent_id varchar(255) not null unique,
    api_key_hash varchar(255) not null,
    max_risk_level varchar(255) check ((max_risk_level in ('LOW','MEDIUM','HIGH','BLOCKED'))),
    name varchar(255) not null,
    primary key (id)
);

create table if not exists approval_request_labels (
    approval_request_id bigint not null,
    labels varchar(255)
);

create table if not exists approval_requests (
    created_at timestamp(6) with time zone,
    decided_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    runtime_notified_at timestamp(6) with time zone,
    delegated_by varchar(500),
    reason varchar(1000),
    action varchar(255),
    agent_id varchar(255),
    decided_by varchar(255),
    execution_id varchar(255),
    risk_level varchar(255) check ((risk_level in ('LOW','MEDIUM','HIGH','BLOCKED'))),
    status varchar(255) check ((status in ('PENDING','APPROVED','REJECTED'))),
    target varchar(255),
    primary key (id)
);

create table if not exists audit_log_labels (
    audit_log_id bigint not null,
    labels varchar(255)
);

create table if not exists audit_logs (
    approval_id bigint,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    delegated_by varchar(500),
    action varchar(255),
    agent_id varchar(255),
    basis varchar(255) check ((basis in ('POLICY','AGENT_RISK_CAP','TOOL_NOT_GRANTED','TOOL_BLOCKED','TOOL_REQUIRES_APPROVAL','APPROVAL_REQUESTED'))),
    risk_level varchar(255) check ((risk_level in ('LOW','MEDIUM','HIGH','BLOCKED'))),
    status varchar(255) check ((status in ('ALLOWED','APPROVAL_REQUIRED','BLOCKED'))),
    target varchar(255),
    primary key (id)
);

create table if not exists executions (
    workflow_version integer not null,
    created_at timestamp(6) with time zone,
    finished_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    waiting_approval_id bigint,
    execution_id varchar(64) not null unique,
    error varchar(4000),
    task varchar(4000),
    status varchar(255) check ((status in ('RUNNING','WAITING_APPROVAL','COMPLETED','STOPPED','FAILED'))),
    workflow_id varchar(255),
    agent_versions jsonb,
    primary key (id)
);

create table if not exists mcp_servers (
    enabled boolean not null,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    name varchar(64) not null unique,
    description varchar(1000),
    url varchar(2000) not null,
    headers_encrypted varchar(8000),
    primary key (id)
);

create table if not exists node_executions (
    approval_id bigint,
    execution_id bigint not null,
    finished_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    started_at timestamp(6) with time zone,
    task_id varchar(64) not null,
    error varchar(4000),
    output varchar(4000),
    node_id varchar(255),
    status varchar(255) check ((status in ('RUNNING','WAITING','COMPLETED','FAILED'))),
    step varchar(255),
    primary key (id),
    unique (execution_id, task_id)
);

create table if not exists policies (
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    action_type varchar(255),
    category varchar(255) check ((category in ('PRIVACY','SECURITY','APPROVAL_WORKFLOW'))),
    label varchar(255),
    risk_level varchar(255) check ((risk_level in ('LOW','MEDIUM','HIGH','BLOCKED'))),
    primary key (id)
);

create table if not exists workflow_versions (
    version integer not null,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    workflow_id bigint not null,
    dsl jsonb not null,
    primary key (id),
    unique (workflow_id, version)
);

create table if not exists workflows (
    latest_version integer not null,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    name varchar(255),
    workflow_id varchar(255) not null unique,
    primary key (id)
);

create index if not exists idxrroagelpohp2jfgqx5rif6tsk
   on approval_requests (execution_id);

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fkgf9u4mr4c3utnw4o79t7a5vls') then
        alter table agent_definition_versions add constraint fkgf9u4mr4c3utnw4o79t7a5vls foreign key (agent_id) references agents;
    end if;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fkrlgn8ku319y5qkonfs9fmk3jf') then
        alter table approval_request_labels add constraint fkrlgn8ku319y5qkonfs9fmk3jf foreign key (approval_request_id) references approval_requests;
    end if;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk35msqpftdcawtqevh6iipjklx') then
        alter table audit_log_labels add constraint fk35msqpftdcawtqevh6iipjklx foreign key (audit_log_id) references audit_logs;
    end if;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fkfyis8qv1b34fi7rf1g5xt8jwf') then
        alter table node_executions add constraint fkfyis8qv1b34fi7rf1g5xt8jwf foreign key (execution_id) references executions;
    end if;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fkn9ngctl0vpolhxt809kaddxr') then
        alter table workflow_versions add constraint fkn9ngctl0vpolhxt809kaddxr foreign key (workflow_id) references workflows;
    end if;
end $$;
