-- Console users and their roles (ADMIN, EDITOR, APPROVER, VIEWER).
-- The first administrator is created at startup from agentgate.admin.* when the table is empty.

create table users (
    enabled boolean not null,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    username varchar(64) not null unique,
    display_name varchar(255),
    password_hash varchar(255) not null,
    primary key (id)
);

create table user_roles (
    user_id bigint not null,
    role varchar(32) not null check (role in ('ADMIN', 'EDITOR', 'APPROVER', 'VIEWER')),
    primary key (user_id, role)
);

alter table user_roles add constraint fk_user_roles_user foreign key (user_id) references users on delete cascade;
